branchName: '${issue.number}'
branches:
  - label: '👏 회의'
    skip: true
  - label: '✨ 리팩터링'
    prefix: refactor/
  - label: '🐞 버그'
    prefix: bugfix/
  - label: '🚨 긴급'
    prefix: hotfix/
  - label: '*'
    prefix: feat/
autoCloseIssue: true
commentMessage: 'Branch ${branchName} create for issue: ${issue.number}'
