server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 907891743241-5mdptr32ec636tla2f78jiuu9snvgm21.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
          kakao:
            client-id: a1f56c996700414e8c59bf2f331d8091
            client-secret: q5c7qOp7wHJb4BlGURIWoeti6UvJZm9c
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
  secret-key: kergpk312pokpoerkopk65pkoi8pokp34okp89okpo32kpotrkvczdffdkopkpo214kpok65op54kpo32k12po4567887433457
  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh
